services:
  - type: web
    name: cineverse
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 120 app:app
    envVars:
      - key: SECRET_KEY
        value: cineverse-secret-key-2024
      - key: OMDB_API_KEY
        value: 94475d77